### ISSUE TITLE
Migrate to Vue.js frontend

### ISSUE THREAD

**Issue by nskoretz** [HugoKlepsch/inventoryBackend#34]
Migrate the front-end to a Vue Single-Page Application.

This means that Flask will only be serving the root endpoint (/) and the API endpoints (api/*). All other page navigation will become <router-links> and be handled by Vue and vue-router.

This means quite a few changes to the toolset, we will have to integrate npm, Webpack, Babel and perhaps the Vue.cli if we want to do Vue components correctly with full functionality.

- [x] [ #35 ] Integrate the Vue.cli with setup.sh and our current environment setup
- [x] [ #36 ] Scaffold a Vue project in /vue
- [x] [ #47 ] Merge Vue directory into server directory
- [x] [ #48 ] Install npm packages in dockerfile. 
- [x] [ #46 ] Stop serving html pages from flask
- [x] [ #37 ] Replace the login page with a Vue page
- [x] [ #38 ] Integrate our stylesheets with Vue, scoped Styles
- [x] [ #53 ] Convert existing JS to vue typescript
- [x] [ #39 ] Replace the signup page with Vue
- [x] [ #40 ] Replace main page with Vue

**Comment by HugoKlepsch** [comment]
Nice.
