### ISSUE TITLE
Develop Item CRUD api

### ISSUE THREAD

**Issue by HugoKlepsch** [HugoKlepsch/inventoryBackend#42]
Should be entirely JSON, input and output
- [x] [ #59 ] item delete 
- [x] [ #58 ] item update
- [x] [ #57 ] item read 
- [x] [ #56 ] and [ #73 ] item create

**Comment by jsovernigo** [comment]
- [ ] #56 Create Completion Required
- [ ] #57 Read Completion Required
- [ ] #58 Update Completion Required
- [ ] #59 Delete Completion Required
